name: Python Script CI

# Give workflow permission to push changes
permissions:
  contents: write

on:
  push:
    branches:
      - JenkinsBranch
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout the branch
    - name: Checkout JenkinsBranch
      uses: actions/checkout@v4
      with:
        ref: JenkinsBranch
        persist-credentials: true

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    # Show runner time
    - name: Show runner time
      run: |
        echo "Current UTC time:"
        date -u
        echo "Current IST time:"
        date -u -d "+5 hours 30 minutes"
        
    # Run Python script and save output
    - name: Run Python Script and save output
      run: |
        echo "Starting script execution..."
        python scripts/find_tabs.py | tee output.txt
        echo "Script execution completed."

    # Update README.md with latest output
    - name: Update README with output
      run: |
        # Remove old script output section if exists
        sed -i '/## Latest Script Output/,$d' README.md || true
        
        # Append new output
        echo -e "\n## Latest Script Output\n" >> README.md
        cat output.txt >> README.md
        
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update build status [CI]" || echo "No changes"
        git push

    # Upload output as artifact
    - name: Upload output file
      uses: actions/upload-artifact@v4
      with:
        name: script-output
        path: output.txt
        
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Greeting from GitHub Actions"
        body: "Hi" 
        to: "nakshay530@gmail.com"
        from: "chessnitro@gmail.com"